version: '3.4'

services:
  identifier:
    ports:
      - "81:80"
  mocklogin:
    image: lblod/mock-login-service:0.4.0
    environment:
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/organizations/141d9d6b-54af-4d17-b313-8d1c30bc3f5b" # ABB
  virtuoso:
    ports:
      - "8891:8890"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    ports:
      - "5601:5601"
    restart: "no"
  file:
    volumes:
      - /home/dries/Projects/LBLOD/app-digitaal-loket/data/files:/share
  enrich-submission:
    restart: "no"
    volumes:
      - /home/dries/Projects/LBLOD/app-digitaal-loket/data/files/submissions:/share/submissions
      - /home/dries/Projects/LBLOD/app-digitaal-loket/data/static-files/semantic-forms-data:/data/semantic-forms
  database:
    environment:
      LOG_OUTGOING_SPARQL_QUERIES: "true"
      LOG_ACCESS_RIGHTS: "true"
      LOG_INCOMING_SPARQL_QUERIES: "true"
  import:
    volumes:
      - /home/dries/Projects/LBLOD/app-digitaal-loket/data/exports/submissions:/data/imports